
export type MembershipStatus = 'active' | 'inactive' | 'expired' | 'pending' | 'expiring soon';

// Added MembershipType for clarity in forms and data structures
export type MembershipType = 'Basic' | 'Premium' | 'Annual' | 'Monthly' | '6-Month' | 'Class Pass' | 'Other';

export interface MembershipPlan {
  id: string; // e.g., 'plan_basic_monthly'
  name: MembershipType; // e.g., "Basic", "Premium"
  price: number;
  durationMonths: number; // Duration in months (e.g., 1 for monthly, 12 for annual)
  description?: string;
}

export interface Member {
  id: string; // uuid - typically generated by DB
  gymId: string; // uuid, FK to gyms.id - from localStorage or context
  planId?: string | null; // uuid, FK to plans.id - corresponds to MembershipPlan.id
  memberId: string; // User-defined member identifier (e.g., MBR001)
  name: string;
  email?: string | null; // Make email optional as per spec
  membershipStatus: MembershipStatus;
  createdAt: string; // timestamptz
  age?: number | null;
  phoneNumber?: string | null;
  joinDate?: string | null; // timestamptz - should default to today on add
  expiryDate?: string | null; // timestamptz - calculated based on plan
  membershipType?: MembershipType | null; // e.g., 'Monthly', 'Annual', 'Class Pass'
  planPrice?: number | null; // Price of the current plan
}

export interface Announcement {
  id: string; // uuid
  gymId: string; // uuid, FK to gyms.id
  title: string;
  content: string;
  createdAt: string; // timestamptz
  updatedAt?: string | null;
}

export interface Gym {
  id: string; // uuid
  name: string;
  ownerEmail: string;
  ownerUserId?: string | null;
  formattedGymId: string;
  createdAt: string; // timestamptz
  status: string;
}

// Plan type from DB schema - this is different from MembershipPlan used in UI
// This is more for data fetched directly from a `plans` table if it exists
export interface Plan {
  id: string; // uuid
  planName: string;
  price: number; // numeric
  durationMonths?: number | null;
  isActive: boolean;
  planId?: string | null; // user-defined plan identifier like 'basic_monthly'
}


export interface CheckIn { // This is the raw DB record type
  id: string; // uuid
  gymId: string; // uuid, FK to gyms.id
  memberTableId: string; // uuid, FK to members.id
  checkInTime: string; // timestamptz
  checkOutTime?: string | null; // timestamptz
  createdAt: string; // timestamptz
}

// Type for displaying formatted check-in information in the UI
export interface FormattedCheckIn {
  memberTableId: string; // The actual UUID of the member from members table
  memberName: string;
  memberId: string; // The user-facing MBR001 style ID
  checkInTime: Date; // Use Date object for easier manipulation client-side
  gymName: string; // Name of the gym where check-in occurred
}


export interface SuperAdmin {
  id: string; // uuid
  email: string;
  passwordHash: string;
  createdAt: string; // timestamptz
  updatedAt?: string | null; // timestamptz
}


// For chart data
export interface DailyCheckIns {
  date: string;
  count: number;
}

export interface OccupancyData {
  time: string;
  count: number;
}

export interface MembershipDistribution {
  status: string;
  count: number;
}

// Attendance summary for a member
export interface AttendanceSummary {
    totalCheckIns: number;
    lastCheckInTime: Date | null;
    recentCheckIns: Date[]; // List of last 5 check-in dates/times
}
