
export type MembershipStatus = 'active' | 'inactive' | 'expired' | 'pending' | 'expiring soon';

// This remains the user-facing name of a plan category, e.g., "Basic"
export type MembershipType = 'Basic' | 'Premium' | 'Annual' | 'Monthly' | '6-Month' | 'Class Pass' | 'Other';

// Interface for plans fetched from the database
export interface FetchedMembershipPlan {
  uuid: string; // This is plans.id (uuid) - the primary key
  planIdText: string | null; // This is plans.plan_id (text, e.g., BAS0599) - user-defined identifier
  name: MembershipType; // This is plans.plan_name (e.g., "Basic")
  price: number;
  durationMonths: number | null;
}

export interface Member {
  id: string; // uuid - typically generated by DB
  gymId: string; // uuid, FK to gyms.id - from localStorage or context
  planId?: string | null; // uuid, FK to plans.id (uuid) - Stores FetchedMembershipPlan.uuid
  memberId: string; // User-defined member identifier (e.g., MBR001)
  name: string;
  email?: string | null;
  membershipStatus: MembershipStatus;
  createdAt: string; // timestamptz
  age?: number | null;
  phoneNumber?: string | null;
  joinDate?: string | null; // timestamptz - should default to today on add
  expiryDate?: string | null; // timestamptz - calculated based on plan
  membershipType?: MembershipType | null; // User-facing plan name, e.g., "Basic" (from FetchedMembershipPlan.name)
  planPrice?: number | null; // Price of the current plan (from FetchedMembershipPlan.price)
}

export interface Announcement {
  id: string; // uuid
  gymId: string; // uuid, FK to gyms.id
  title: string;
  content: string;
  createdAt: string; // timestamptz
  updatedAt?: string | null;
}

export interface Gym {
  id: string; // uuid
  name: string;
  ownerEmail: string;
  ownerUserId?: string | null;
  formattedGymId: string;
  createdAt: string; // timestamptz
  status: string;
}

export interface Plan { // This is the DB schema type, used internally by Supabase client
  id: string // uuid
  plan_name: string
  price: number // numeric
  duration_months: number | null // int4
  is_active: boolean // bool
  plan_id: string | null // text, User-defined plan identifier
}


export interface CheckIn { // This is the raw DB record type
  id: string; // uuid
  gymId: string; // uuid, FK to gyms.id
  memberTableId: string; // uuid, FK to members.id
  checkInTime: string; // timestamptz
  checkOutTime?: string | null; // timestamptz
  createdAt: string; // timestamptz
}

// Type for displaying formatted check-in information in the UI
export interface FormattedCheckIn {
  memberTableId: string; // The actual UUID of the member from members table
  memberName: string;
  memberId: string; // The user-facing MBR001 style ID
  checkInTime: Date; // Use Date object for easier manipulation client-side
  gymName: string; // Name of the gym where check-in occurred
}


export interface SuperAdmin {
  id: string; // uuid
  email: string;
  passwordHash: string;
  createdAt: string; // timestamptz
  updatedAt?: string | null; // timestamptz
}


// For chart data
export interface DailyCheckIns {
  date: string;
  count: number;
}

export interface OccupancyData {
  time: string;
  count: number;
}

export interface MembershipDistribution {
  status: string;
  count: number;
}

// Attendance summary for a member
export interface AttendanceSummary {
    totalCheckIns: number;
    lastCheckInTime: Date | null;
    recentCheckIns: Date[]; // List of last 5 check-in dates/times
}
